name: emoona
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.6

  # ✅ Firebase dependencies
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.4

  # ✅ Added for date formatting and parsing
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Logo.jpg"

flutter_icon1:
  android: true
  ios: true
  image_path: "assets/icon/118822-200.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/Logo.jpg
    - assets/icon/icon.png
